<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Platforms>x64</Platforms>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="RGB.NET.Core" IncludeAssets="compile;build;buildTransitive" Version="3.1.0" />
        <PackageReference Include="ArtemisRGB.UI.Shared" IncludeAssets="compile;build;buildTransitive" Version="1.2025.1223.3" />
        <PackageReference Include="Zeroconf" Version="3.6.11" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="nanoleaf.png" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="plugin.json" CopyToOutputDirectory="PreserveNewest" />
        <PackageReference Include="ArtemisRGB.Plugins.BuildTask" Version="2.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
